name = "SimString"
uuid = "2e3c4037-312d-4650-b9c0-fcd0fc09aae4"
authors = ["Bernard Brenyah"]
version = "0.1.0"

[deps]
Dictionaries = "85a47980-9c8c-11e8-2b9f-f7ca1fa99fb4"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
